begin;
select plan(15);
select has_table('public','orders','orders exists');
select has_table('public','order_events','events exist');
select has_function('public','transition_order',array['uuid','order_status','text','text'],'transition RPC exists');
select lives_ok($$select public.assert_transition('NEW','CONFIRMED')$$,'legal transition accepted');
select throws_ok($$select public.assert_transition('NEW','DELIVERED')$$,'23514',null,'illegal transition rejected');
select throws_ok($$select public.create_order('{"customer":{"name":"A","primaryPhone":"+998901234567"},"type":"DELIVERY","paymentMethod":"CASH","items":[{"name":"X","unitPrice":1,"quantity":1}]}'::jsonb)$$,'P0001',null,'incomplete delivery rejected');
select lives_ok($$select public.create_order('{"customer":{"name":"A","primaryPhone":"+998901234567"},"type":"PICKUP","paymentMethod":"CASH","items":[{"name":"X","unitPrice":100,"quantity":2,"modifierIds":[],"modifierNames":[]}]}'::jsonb)$$,'pickup without address accepted');
select is((select total from orders order by created_at desc limit 1),200,'total calculated in database');
select is((select count(*)::integer from order_events where order_id=(select id from orders order by created_at desc limit 1)),1,'creation event added');
select is((select count(*)::integer from pg_policies where schemaname='public' and tablename='orders'),1,'orders RLS policy exists');
select is((select relrowsecurity from pg_class where oid='public.orders'::regclass),true,'orders RLS enabled');
select is((select count(*)::integer from pg_publication_tables where pubname='supabase_realtime' and tablename='orders'),1,'orders realtime enabled');
set local role anon;
select throws_ok($$select count(*) from public.orders$$,'42501',null,'anonymous cannot list orders');
select is((select count(*)::integer from public.menu_items)>0,true,'anonymous can read menu');
reset role;
select is((select count(*)::integer from profiles where role='DRIVER'),1,'driver identity seeded');
select * from finish();
rollback;
