import {createContext,useCallback,useContext,useEffect,useMemo,useState,type ReactNode} from 'react'
import {store} from './data'
import type {ActorType,CartItem,DeliveryIssueType,Driver,Order,OrderStatus} from './domain'

const terminalStatuses:OrderStatus[]=['DELIVERED','DELIVERY_FAILED','RETURNED','CANCELLED']
type State={orders:Order[];drivers:Driver[];cart:CartItem[];loaded:boolean;refresh:()=>Promise<void>;addToCart:(item:CartItem)=>void;updateQuantity:(id:string,delta:number)=>void;clearCart:()=>void;submitOrder:(order:Order)=>Promise<void>;transition:(id:string,to:OrderStatus,actor:ActorType,reason?:string)=>Promise<void>;assign:(orderId:string,driverId:string)=>Promise<void>;acceptAssignment:(orderId:string)=>Promise<void>;setEstimate:(orderId:string,minutes:number)=>Promise<void>;reportIssue:(orderId:string,type:DeliveryIssueType,description:string,reporter:string)=>Promise<void>;resolveIssue:(orderId:string,issueId:string)=>Promise<void>}
const C=createContext<State|null>(null)
export function AppProvider({children}:{children:ReactNode}){const[orders,setOrders]=useState<Order[]>([]);const[drivers,setDrivers]=useState<Driver[]>([]);const[cart,setCart]=useState<CartItem[]>([]);const[loaded,setLoaded]=useState(false);const refresh=useCallback(async()=>{setOrders(await store.list());setDrivers(await store.listDrivers());setLoaded(true)},[]);useEffect(()=>{void refresh();return store.subscribe(()=>void refresh())},[refresh]);const value=useMemo<State>(()=>({orders,drivers,cart,loaded,refresh,addToCart:item=>setCart(c=>{const old=c.find(x=>x.menuItemId===item.menuItemId&&x.modifierIds.join()===item.modifierIds.join());return old?c.map(x=>x.id===old.id?{...x,quantity:x.quantity+item.quantity}:x):[...c,item]}),updateQuantity:(id,delta)=>setCart(c=>c.map(x=>x.id===id?{...x,quantity:x.quantity+delta}:x).filter(x=>x.quantity>0)),clearCart:()=>setCart([]),submitOrder:async order=>{await store.save(order);await refresh()},transition:async(id,to,actor,reason)=>{const order=await store.get(id);if(!order)throw new Error('Order not found');await store.transition(id,to,actor,reason);if(terminalStatuses.includes(to)&&order.assignedDriverId&&'saveDriver'in store){const driver=drivers.find(d=>d.id===order.assignedDriverId);if(driver)await store.saveDriver({...driver,availability:'AVAILABLE'})}await refresh()},assign:async(orderId,driverId)=>{const order=await store.get(orderId);const driver=drivers.find(d=>d.id===driverId);if(!order||!driver)throw new Error('Order or driver not found');await store.assign(order,driver);await refresh()},acceptAssignment:async orderId=>{await store.acceptAssignment(orderId);await refresh()},setEstimate:async(orderId,minutes)=>{await store.setEstimate(orderId,minutes);await refresh()},reportIssue:async(orderId,type,description,reporter)=>{await store.reportIssue(orderId,type,description,reporter);await refresh()},resolveIssue:async(orderId,issueId)=>{await store.resolveIssue(orderId,issueId);await refresh()}}),[orders,drivers,cart,loaded,refresh]);return <C.Provider value={value}>{children}</C.Provider>}
export function useApp(){const c=useContext(C);if(!c)throw new Error('AppProvider missing');return c}
