create extension if not exists pgcrypto with schema extensions;
create type public.app_role as enum ('RESTAURANT','DISPATCHER','DRIVER');
create type public.order_status as enum ('NEW','CONFIRMED','PREPARING','READY','DRIVER_ASSIGNED','PICKED_UP','ON_THE_WAY','ARRIVED','DELIVERED','REJECTED','CANCELLED','DELIVERY_FAILED','RETURNED');
create type public.order_type as enum ('DELIVERY','PICKUP');
create type public.actor_type as enum ('CUSTOMER','RESTAURANT','DISPATCHER','DRIVER','SYSTEM');
create type public.payment_method as enum ('CASH','CARD_ON_DELIVERY');
create type public.payment_collection_status as enum ('NOT_REQUIRED','PENDING','COLLECTED','FAILED');
create type public.address_confidence as enum ('COMPLETE','NEEDS_CLARIFICATION','CUSTOMER_CONFIRMATION_REQUIRED');
create type public.driver_availability as enum ('AVAILABLE','BUSY','OFFLINE');
create type public.delivery_issue_type as enum ('ADDRESS_INCORRECT','CUSTOMER_NOT_ANSWERING','PAYMENT_PROBLEM','ADDRESS_CLARIFICATION');
create sequence public.order_number_seq start 1043;

create table public.profiles(id uuid primary key references auth.users(id) on delete cascade,role app_role not null,display_name text not null,phone text,created_at timestamptz not null default now());
create table public.menu_categories(id text primary key,name text not null,description text not null default '',sort_order integer not null default 0,active boolean not null default true);
create table public.menu_items(id text primary key,category_id text not null references menu_categories(id),name text not null,description text not null default '',price integer not null check(price>=0),image text not null default '',available boolean not null default true,sort_order integer not null default 0);
create table public.menu_modifiers(id text primary key,menu_item_id text not null references menu_items(id) on delete cascade,name text not null,price integer not null default 0 check(price>=0),available boolean not null default true);
create table public.drivers(id uuid primary key references profiles(id) on delete cascade,phone text not null,vehicle text not null,availability driver_availability not null default 'OFFLINE',updated_at timestamptz not null default now());
create table public.orders(id uuid primary key default gen_random_uuid(),number text not null unique,tracking_token uuid not null default gen_random_uuid() unique,customer_name text not null,primary_phone text not null,secondary_phone text,order_type order_type not null,payment_method payment_method not null,payment_status payment_collection_status not null default 'PENDING',special_instructions text not null default '',status order_status not null default 'NEW',subtotal integer not null check(subtotal>=0),delivery_fee integer not null default 0 check(delivery_fee>=0),total integer generated always as(subtotal+delivery_fee) stored,estimated_minutes integer check(estimated_minutes between 5 and 180),assigned_driver_id uuid references drivers(id),assignment_accepted_at timestamptz,rejection_reason text,cancellation_reason text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index orders_status_created_idx on orders(status,created_at desc);create index orders_driver_status_idx on orders(assigned_driver_id,status);
create table public.customer_addresses(order_id uuid primary key references orders(id) on delete cascade,district text not null,street text not null,house text not null,entrance text,floor text,apartment text,landmark text not null default '',delivery_notes text not null default '',latitude double precision not null check(latitude between -90 and 90),longitude double precision not null check(longitude between -180 and 180),confidence address_confidence not null default 'COMPLETE');
create table public.order_items(id uuid primary key default gen_random_uuid(),order_id uuid not null references orders(id) on delete cascade,menu_item_id text references menu_items(id),name text not null,unit_price integer not null check(unit_price>=0),quantity integer not null check(quantity>0),modifier_ids text[] not null default '{}',modifier_names text[] not null default '{}',instructions text not null default '',total integer generated always as(unit_price*quantity) stored);
create table public.driver_assignments(id uuid primary key default gen_random_uuid(),order_id uuid not null unique references orders(id),driver_id uuid not null references drivers(id),assigned_by uuid references profiles(id),assigned_at timestamptz not null default now(),accepted_at timestamptz,ended_at timestamptz);
create table public.order_events(id uuid primary key default gen_random_uuid(),order_id uuid not null references orders(id) on delete cascade,actor_type actor_type not null,actor_id text not null,previous_status order_status,new_status order_status not null,occurred_at timestamptz not null default now(),reason text,notes text);
create index order_events_order_time_idx on order_events(order_id,occurred_at);
create table public.delivery_issues(id uuid primary key default gen_random_uuid(),order_id uuid not null references orders(id) on delete cascade,issue_type delivery_issue_type not null,description text not null check(length(trim(description))>0),reported_by uuid references profiles(id),created_at timestamptz not null default now(),resolved_at timestamptz,resolved_by uuid references profiles(id));

create function public.current_app_role() returns app_role language sql stable security definer set search_path=public as $$select role from profiles where id=auth.uid()$$;
create function public.is_staff() returns boolean language sql stable security definer set search_path=public as $$select coalesce(current_app_role() = any(array['RESTAURANT','DISPATCHER']::app_role[]),false)$$;
create function public.touch_updated_at() returns trigger language plpgsql set search_path=public as $$begin new.updated_at=now();return new;end$$;
create trigger orders_touch before update on orders for each row execute function touch_updated_at();create trigger drivers_touch before update on drivers for each row execute function touch_updated_at();
create function public.assert_transition(p_from order_status,p_to order_status) returns void language plpgsql immutable set search_path=public as $$begin if not (case p_from when 'NEW' then p_to in ('CONFIRMED','REJECTED','CANCELLED') when 'CONFIRMED' then p_to in ('PREPARING','CANCELLED') when 'PREPARING' then p_to in ('READY','CANCELLED') when 'READY' then p_to in ('DRIVER_ASSIGNED','DELIVERED','CANCELLED') when 'DRIVER_ASSIGNED' then p_to in ('PICKED_UP','CANCELLED') when 'PICKED_UP' then p_to in ('ON_THE_WAY','DELIVERY_FAILED','RETURNED') when 'ON_THE_WAY' then p_to in ('ARRIVED','DELIVERY_FAILED','RETURNED') when 'ARRIVED' then p_to in ('DELIVERED','DELIVERY_FAILED','RETURNED') when 'DELIVERY_FAILED' then p_to='RETURNED' else false end) then raise exception 'Illegal transition: % -> %',p_from,p_to using errcode='23514';end if;end$$;

create function public.create_order(p_order jsonb) returns jsonb language plpgsql security definer set search_path=public,extensions as $$declare oid uuid:=coalesce((p_order->>'id')::uuid,gen_random_uuid());num text;sub integer;typ order_type:=(p_order->>'type')::order_type;a jsonb:=p_order->'address';i jsonb;begin if jsonb_array_length(coalesce(p_order->'items','[]'))=0 then raise exception 'At least one item is required';end if;select coalesce(sum((x->>'unitPrice')::integer*(x->>'quantity')::integer),0) into sub from jsonb_array_elements(p_order->'items') x;if typ='DELIVERY' and (coalesce(a->>'district','')='' or coalesce(a->>'street','')='' or coalesce(a->>'house','')='' or (coalesce(a->>'landmark','')='' and coalesce(a->>'deliveryNotes','')='') or a->>'latitude' is null or a->>'longitude' is null) then raise exception 'Complete delivery address and coordinates are required';end if;num:='ZG-'||lpad(nextval('order_number_seq')::text,4,'0');insert into orders(id,number,customer_name,primary_phone,secondary_phone,order_type,payment_method,special_instructions,subtotal,delivery_fee) values(oid,num,trim(p_order#>>'{customer,name}'),trim(p_order#>>'{customer,primaryPhone}'),nullif(trim(p_order#>>'{customer,secondaryPhone}'),''),typ,(p_order->>'paymentMethod')::payment_method,coalesce(p_order->>'specialInstructions',''),sub,case when typ='DELIVERY' then coalesce((p_order->>'deliveryFee')::integer,0) else 0 end);if typ='DELIVERY' then insert into customer_addresses values(oid,a->>'district',a->>'street',a->>'house',nullif(a->>'entrance',''),nullif(a->>'floor',''),nullif(a->>'apartment',''),coalesce(a->>'landmark',''),coalesce(a->>'deliveryNotes',''),(a->>'latitude')::float8,(a->>'longitude')::float8,coalesce((a->>'confidence')::address_confidence,'COMPLETE'));end if;for i in select * from jsonb_array_elements(p_order->'items') loop insert into order_items(order_id,menu_item_id,name,unit_price,quantity,modifier_ids,modifier_names,instructions) values(oid,nullif(i->>'menuItemId',''),i->>'name',(i->>'unitPrice')::integer,(i->>'quantity')::integer,array(select jsonb_array_elements_text(coalesce(i->'modifierIds','[]'))),array(select jsonb_array_elements_text(coalesce(i->'modifierNames','[]'))),coalesce(i->>'instructions',''));end loop;insert into order_events(order_id,actor_type,actor_id,new_status) values(oid,'CUSTOMER','guest','NEW');return (select jsonb_build_object('id',id,'number',number,'trackingToken',tracking_token) from orders where id=oid);end$$;

create function public.transition_order(p_order_id uuid,p_new_status order_status,p_reason text default null,p_notes text default null) returns orders language plpgsql security definer set search_path=public as $$declare o orders;old order_status;actor actor_type;begin select * into o from orders where id=p_order_id for update;if not found then raise exception 'Order not found';end if;old:=o.status;if current_app_role()='DRIVER' then if o.assigned_driver_id<>auth.uid() then raise exception 'Driver is not assigned';end if;actor:='DRIVER';elsif current_app_role()='DISPATCHER' then actor:='DISPATCHER';elsif current_app_role()='RESTAURANT' then actor:='RESTAURANT';else raise exception 'Authentication required';end if;perform assert_transition(old,p_new_status);if p_new_status in ('REJECTED','CANCELLED','DELIVERY_FAILED') and coalesce(trim(p_reason),'')='' then raise exception 'Reason is required';end if;update orders set status=p_new_status,rejection_reason=case when p_new_status='REJECTED' then p_reason else rejection_reason end,cancellation_reason=case when p_new_status='CANCELLED' then p_reason else cancellation_reason end,payment_status=case when p_new_status='DELIVERED' and payment_method='CASH' then 'COLLECTED' else payment_status end where id=p_order_id returning * into o;insert into order_events(order_id,actor_type,actor_id,previous_status,new_status,reason,notes) values(p_order_id,actor,auth.uid()::text,old,p_new_status,p_reason,p_notes);if p_new_status in ('DELIVERED','DELIVERY_FAILED','RETURNED','CANCELLED') and o.assigned_driver_id is not null then update drivers set availability='AVAILABLE' where id=o.assigned_driver_id;update driver_assignments set ended_at=now() where order_id=p_order_id;end if;return o;end$$;
create function public.assign_driver(p_order_id uuid,p_driver_id uuid) returns driver_assignments language plpgsql security definer set search_path=public as $$declare o orders;d drivers;a driver_assignments;begin if not is_staff() then raise exception 'Staff role required';end if;select * into o from orders where id=p_order_id for update;perform assert_transition(o.status,'DRIVER_ASSIGNED');select * into d from drivers where id=p_driver_id for update;if d.availability<>'AVAILABLE' then raise exception 'Driver is not available';end if;insert into driver_assignments(order_id,driver_id,assigned_by) values(p_order_id,p_driver_id,auth.uid()) returning * into a;update drivers set availability='BUSY' where id=p_driver_id;update orders set assigned_driver_id=p_driver_id,status='DRIVER_ASSIGNED' where id=p_order_id;insert into order_events(order_id,actor_type,actor_id,previous_status,new_status) values(p_order_id,'DISPATCHER',auth.uid()::text,'READY','DRIVER_ASSIGNED');return a;end$$;
create function public.accept_assignment(p_order_id uuid) returns driver_assignments language plpgsql security definer set search_path=public as $$declare a driver_assignments;begin update driver_assignments set accepted_at=now() where order_id=p_order_id and driver_id=auth.uid() and accepted_at is null returning * into a;if not found then raise exception 'Assignment not found';end if;update orders set assignment_accepted_at=a.accepted_at where id=p_order_id;return a;end$$;
create function public.report_delivery_issue(p_order_id uuid,p_type delivery_issue_type,p_description text) returns delivery_issues language plpgsql security definer set search_path=public as $$declare i delivery_issues;begin if not is_staff() and not exists(select 1 from orders where id=p_order_id and assigned_driver_id=auth.uid()) then raise exception 'Not authorized';end if;insert into delivery_issues(order_id,issue_type,description,reported_by) values(p_order_id,p_type,p_description,auth.uid()) returning * into i;return i;end$$;
create function public.resolve_delivery_issue(p_issue_id uuid) returns delivery_issues language plpgsql security definer set search_path=public as $$declare i delivery_issues;begin if not is_staff() then raise exception 'Staff role required';end if;update delivery_issues set resolved_at=now(),resolved_by=auth.uid() where id=p_issue_id and resolved_at is null returning * into i;if not found then raise exception 'Open issue not found';end if;return i;end$$;
create function public.set_preparation_estimate(p_order_id uuid,p_minutes integer) returns orders language plpgsql security definer set search_path=public as $$declare o orders;begin if not is_staff() then raise exception 'Staff role required';end if;if p_minutes not between 5 and 180 then raise exception 'Estimate must be 5-180 minutes';end if;update orders set estimated_minutes=p_minutes where id=p_order_id returning * into o;return o;end$$;

alter table profiles enable row level security;alter table menu_categories enable row level security;alter table menu_items enable row level security;alter table menu_modifiers enable row level security;alter table drivers enable row level security;alter table orders enable row level security;alter table customer_addresses enable row level security;alter table order_items enable row level security;alter table driver_assignments enable row level security;alter table order_events enable row level security;alter table delivery_issues enable row level security;
create policy profile_read on profiles for select to authenticated using(id=auth.uid() or is_staff());create policy category_read on menu_categories for select to anon,authenticated using(active);create policy menu_read on menu_items for select to anon,authenticated using(available);create policy modifier_read on menu_modifiers for select to anon,authenticated using(available);create policy driver_read on drivers for select to authenticated using(id=auth.uid() or is_staff());create policy order_read on orders for select to authenticated using(is_staff() or assigned_driver_id=auth.uid());create policy address_read on customer_addresses for select to authenticated using(exists(select 1 from orders o where o.id=order_id and(is_staff() or o.assigned_driver_id=auth.uid())));create policy item_read on order_items for select to authenticated using(exists(select 1 from orders o where o.id=order_id and(is_staff() or o.assigned_driver_id=auth.uid())));create policy assignment_read on driver_assignments for select to authenticated using(is_staff() or driver_id=auth.uid());create policy event_read on order_events for select to authenticated using(exists(select 1 from orders o where o.id=order_id and(is_staff() or o.assigned_driver_id=auth.uid())));create policy issue_read on delivery_issues for select to authenticated using(exists(select 1 from orders o where o.id=order_id and(is_staff() or o.assigned_driver_id=auth.uid())));
revoke all on all tables in schema public from anon,authenticated;grant select on menu_categories,menu_items,menu_modifiers to anon,authenticated;grant select on profiles,drivers,orders,customer_addresses,order_items,driver_assignments,order_events,delivery_issues to authenticated;grant execute on function create_order(jsonb) to anon,authenticated;grant execute on function transition_order(uuid,order_status,text,text),assign_driver(uuid,uuid),accept_assignment(uuid),report_delivery_issue(uuid,delivery_issue_type,text),resolve_delivery_issue(uuid),set_preparation_estimate(uuid,integer) to authenticated;
alter publication supabase_realtime add table orders,order_events,driver_assignments,delivery_issues,drivers;
