-- Expose customer-facing terminal reasons through the existing
-- capability-gated tracking response. Private contact, address and driver
-- fields remain redacted exactly as before.
create or replace function public.get_order_tracking(p_order_id uuid,p_tracking_token uuid)
returns jsonb language sql stable security definer set search_path=public as $$
select jsonb_build_object('id',o.id,'number',o.number,'customer_name','','primary_phone','','order_type',o.order_type,'payment_method',o.payment_method,'payment_status',o.payment_status,'special_instructions','','status',o.status,'rejection_reason',o.rejection_reason,'cancellation_reason',o.cancellation_reason,'delivery_review_status',o.delivery_review_status,'delivery_review_reason',o.delivery_review_reason,'subtotal',o.subtotal,'packaging_total',o.packaging_total,'delivery_fee',o.delivery_fee,'total',o.total,'estimated_minutes',o.estimated_minutes,'assigned_driver_id',null,'assignment_accepted_at',null,'created_at',o.created_at,'restaurant_name',s.restaurant_display_name,'restaurant_address',s.restaurant_address,'restaurant_phone',s.restaurant_phone,'customer_addresses','[]'::jsonb,'order_items',(select coalesce(jsonb_agg(jsonb_build_object('id',i.id,'order_id',i.order_id,'menu_item_id',i.menu_item_id,'name',i.name,'unit_price',i.unit_price,'quantity',i.quantity,'modifier_ids',i.modifier_ids,'modifier_names',i.modifier_names,'instructions',i.instructions,'total',i.total,'packaging_box_count',i.packaging_box_count,'packaging_unit_price',i.packaging_unit_price,'packaging_capacity',i.packaging_capacity,'packaging_total',i.packaging_total)),'[]'::jsonb)from public.order_items i where i.order_id=o.id),'order_events',(select coalesce(jsonb_agg(jsonb_build_object('id',e.id,'order_id',e.order_id,'actor_type','SYSTEM','actor_id','public','previous_status',e.previous_status,'new_status',e.new_status,'reason',case when e.notes='DELIVERY_REVIEW_REJECTED' then e.reason else null end,'notes',e.notes,'occurred_at',e.occurred_at)order by e.occurred_at),'[]'::jsonb)from public.order_events e where e.order_id=o.id),'delivery_issues','[]'::jsonb,'feedback',(select jsonb_build_object('deliveryRating',f.delivery_rating,'deliveryIssueReason',f.delivery_issue_reason,'foodRating',f.food_rating,'foodIssueReason',f.food_issue_reason,'comment',f.comment,'submittedAt',f.submitted_at)from public.order_feedback f where f.order_id=o.id))from public.orders o cross join public.delivery_settings s where s.id=true and o.id=p_order_id and o.tracking_token=p_tracking_token
$$;
revoke execute on function public.get_order_tracking(uuid,uuid) from public;
grant execute on function public.get_order_tracking(uuid,uuid) to anon,authenticated;
