import type{AddressSuggestion,GeocodingResult,MapCoordinate,MapLocationSelection,MapProvider}from'./types'
export const isValidCoordinate=({latitude,longitude}:MapCoordinate)=>Number.isFinite(latitude)&&Number.isFinite(longitude)&&latitude>=-90&&latitude<=90&&longitude>=-180&&longitude<=180&&!(latitude===0&&longitude===0)
export const haversineKm=(a:MapCoordinate,b:MapCoordinate)=>{const rad=(n:number)=>n*Math.PI/180;const dLat=rad(b.latitude-a.latitude),dLng=rad(b.longitude-a.longitude);const x=Math.sin(dLat/2)**2+Math.cos(rad(a.latitude))*Math.cos(rad(b.latitude))*Math.sin(dLng/2)**2;return 6371*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
export const deliveryFee=(subtotal:number,baseFee:number,freeThreshold?:number|null)=>freeThreshold!=null&&subtotal>=freeThreshold?0:baseFee
export const deliveryZoneEligibility=(orderType:'DELIVERY'|'PICKUP',distanceKm:number|undefined,enabled:boolean,maxRadiusKm:number)=>orderType==='PICKUP'?{eligible:true,zoneResult:'ELIGIBLE' as const}:!enabled?{eligible:false,zoneResult:'DELIVERY_DISABLED' as const}:{eligible:distanceKm!==undefined&&distanceKm<=maxRadiusKm,zoneResult:distanceKm!==undefined&&distanceKm<=maxRadiusKm?'ELIGIBLE' as const:'OUTSIDE_ZONE' as const}
export const initialSelection=(provider:MapProvider):MapLocationSelection=>({provider,state:'NOT_SELECTED'})
export const selectCoordinate=(current:MapLocationSelection,coordinate:MapCoordinate):MapLocationSelection=>({provider:current.provider,coordinate,state:current.confirmedAt?'NEEDS_RECONFIRMATION':'SELECTED'})
export const beginReverse=(current:MapLocationSelection):MapLocationSelection=>({...current,state:'REVERSE_GEOCODING',error:undefined})
export const receiveSuggestion=(current:MapLocationSelection,suggestion:GeocodingResult|null):MapLocationSelection=>({...current,suggestion:suggestion?{...suggestion,label:suggestion.formattedAddress}:undefined,state:current.state==='NEEDS_RECONFIRMATION'?'NEEDS_RECONFIRMATION':suggestion?'SUGGESTION_AVAILABLE':'SELECTED'})
export const confirmSelection=(current:MapLocationSelection):MapLocationSelection=>{if(!current.coordinate||!isValidCoordinate(current.coordinate))throw new Error('Valid coordinates required');return{...current,state:'CONFIRMED',confirmedAt:new Date().toISOString(),error:undefined}}
export const materialAddressChange=(current:MapLocationSelection):MapLocationSelection=>current.confirmedAt?{...current,state:'NEEDS_RECONFIRMATION',confirmedAt:undefined}:current
export const applySuggestion=<T extends{district:string;street:string;house:string}>(address:T,suggestion:AddressSuggestion):T=>({...address,district:suggestion.district||address.district,street:suggestion.street||address.street,house:suggestion.house||address.house})
export const addressConfidence=(selection:MapLocationSelection,requiredComplete:boolean,inZone:boolean,warning=false)=>!selection.confirmedAt||selection.state==='NEEDS_RECONFIRMATION'?'CUSTOMER_CONFIRMATION_REQUIRED':requiredComplete&&inZone&&!warning?'COMPLETE':'NEEDS_CLARIFICATION'
