import{describe,expect,it}from'vitest'
import{addressConfidence,applySuggestion,confirmSelection,deliveryFee,deliveryZoneEligibility,haversineKm,initialSelection,isValidCoordinate,materialAddressChange,receiveSuggestion,selectCoordinate}from'./core'
import{createMapAdapter}from'./factory'
import{navigationUrl}from'./navigation'
import{YandexMapAdapter}from'./yandex'

describe('map provider selection',()=>{it('selects deterministic mock explicitly',()=>expect(createMapAdapter('mock').provider).toBe('mock'));it('rejects missing Yandex configuration',()=>expect(()=>new YandexMapAdapter('')).toThrow(/API_KEY/))})
describe('coordinates and selection states',()=>{it('validates real ranges and rejects zero fallback',()=>{expect(isValidCoordinate({latitude:40.1,longitude:65.3})).toBe(true);expect(isValidCoordinate({latitude:91,longitude:65})).toBe(false);expect(isValidCoordinate({latitude:0,longitude:0})).toBe(false)});it('moves through selection, suggestion and confirmation',()=>{let s=selectCoordinate(initialSelection('mock'),{latitude:40.1,longitude:65.3});expect(s.state).toBe('SELECTED');s=receiveSuggestion(s,{coordinate:s.coordinate!,formattedAddress:'Navoiy'});expect(s.state).toBe('SUGGESTION_AVAILABLE');s=confirmSelection(s);expect(s.state).toBe('CONFIRMED');expect(s.confirmedAt).toBeTruthy()});it('requires reconfirmation after a material change',()=>{const confirmed=confirmSelection(selectCoordinate(initialSelection('mock'),{latitude:40.1,longitude:65.3}));expect(materialAddressChange(confirmed)).toMatchObject({state:'NEEDS_RECONFIRMATION',confirmedAt:undefined})});it('keeps reconfirmation required after reverse geocoding a moved pin',()=>{const confirmed=confirmSelection(selectCoordinate(initialSelection('mock'),{latitude:40.1,longitude:65.3}));const moved=selectCoordinate(confirmed,{latitude:40.11,longitude:65.31});expect(receiveSuggestion(moved,{coordinate:moved.coordinate!,formattedAddress:'Moved'}).state).toBe('NEEDS_RECONFIRMATION')})})
describe('address and navigation helpers',()=>{it('applies only populated suggested structured fields',()=>expect(applySuggestion({district:'Old',street:'Manual',house:'9'},{label:'X',formattedAddress:'X',coordinate:{latitude:1,longitude:1},district:'New',street:undefined,house:'10'})).toEqual({district:'New',street:'Manual',house:'10'}));it('generates encoded destination-only navigation URLs',()=>{expect(navigationUrl('yandex',{latitude:40.1,longitude:65.3})).toContain('40.100000%2C65.300000');expect(navigationUrl('google',{latitude:40.1,longitude:65.3})).toContain('destination=40.100000%2C65.300000')});it('calculates geographic distance',()=>expect(haversineKm({latitude:40.1039,longitude:65.3688},{latitude:40.1039,longitude:65.3688})).toBe(0));it('calculates base and free delivery fees',()=>{expect(deliveryFee(50000,10000,150000)).toBe(10000);expect(deliveryFee(150000,10000,150000)).toBe(0)});it('lets pickup bypass disabled and unknown delivery-zone checks',()=>expect(deliveryZoneEligibility('PICKUP',undefined,false,0)).toEqual({eligible:true,zoneResult:'ELIGIBLE'}));it('calculates understandable confidence states',()=>{const selected=selectCoordinate(initialSelection('mock'),{latitude:40.1,longitude:65.3});expect(addressConfidence(selected,true,true)).toBe('CUSTOMER_CONFIRMATION_REQUIRED');expect(addressConfidence(confirmSelection(selected),true,true)).toBe('COMPLETE');expect(addressConfidence(confirmSelection(selected),false,true)).toBe('NEEDS_CLARIFICATION')})})
